// Internal (admin-1 / state-province) borders.
//
// The data lives in public/admin1/ as one file per country, generated by
// scripts/build-admin1-borders.mjs from Natural Earth 10m data. We fetch only the
// country currently on screen (~14-90 KB, ~27 KB gzipped for India) so this costs
// nothing in the JS bundle and nothing at all for maps that don't show borders.

/** A line is a list of [lng, lat] pairs. */
export type BorderLine = [number, number][];

const cache = new Map<string, BorderLine[]>();
let indexPromise: Promise<Set<string>> | null = null;

/** Must stay in sync with slugify() in scripts/build-admin1-borders.mjs */
export function admin1Slug(name: string): string {
  return name
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

async function loadIndex(): Promise<Set<string>> {
  if (!indexPromise) {
    indexPromise = fetch('/admin1/index.json')
      .then((r) => (r.ok ? r.json() : []))
      .then((slugs: string[]) => new Set(slugs))
      .catch(() => new Set<string>());
  }
  return indexPromise;
}

/** Border lines for one country. Returns [] when the country has no admin-1 data. */
export async function loadAdmin1Lines(countryName: string): Promise<BorderLine[]> {
  const slug = admin1Slug(countryName);
  const cached = cache.get(slug);
  if (cached) return cached;

  const index = await loadIndex();
  if (!index.has(slug)) {
    cache.set(slug, []);
    return [];
  }
  try {
    const res = await fetch(`/admin1/${slug}.json`);
    if (!res.ok) throw new Error(`admin1 fetch failed: ${res.status}`);
    const lines = (await res.json()) as BorderLine[];
    cache.set(slug, lines);
    return lines;
  } catch {
    cache.set(slug, []);
    return [];
  }
}

/** Merged border lines for several countries (used by multi-country regions). */
export async function loadAdmin1LinesFor(countryNames: string[]): Promise<BorderLine[]> {
  const groups = await Promise.all(countryNames.map(loadAdmin1Lines));
  return groups.flat();
}
