[general]
persistentmembers = yes
autofill = yes
monitor-type = MixMonitor

[support_queue]
musicclass = default
strategy = rrmemory       ; Round Robin Memory (routes to the agent who has been idle the longest)
joinempty = yes           ; Allow callers to join even if no agents are logged in
leavewhenempty = no
ringinuse = no            ; Don't ring an agent if they are already on a call
timeout = 15              ; How long to ring an agent before trying the next one
retry = 5                 ; How long to wait before trying the next agent
wrapuptime = 10           ; Give the agent 10 seconds of breathing room after a call ends
announce-frequency = 30   ; Announce queue position every 30 seconds
announce-holdtime = yes   ; Tell the caller their estimated hold time

; Hardcoded members (agents)
member => PJSIP/webrtc_client
